<?php

/**
 * Implementation of hook_init().
 */
function modal_init() {
if (drupal_is_front_page()) {
    $message = "<a id='prev'>Previous</a><a id='next'>Next</a><div id='slider'>
      <ul>
        <li style='display:block'><h2>Drupal puts your content first</h2><p>Drupal is all about managing and displaying your content the way you want. Each piece of content is a <em>node</em>.<p>In this walkthrough, lets pretend you are building a newspapers website</p></li>
        <li style='display:none'><h2>Drupal has content types</h2><p>Lets say our newspaper website has articles, events and photos.<p>
        <p>Each of these would be a <em>content type</em></p>
        <p>This would allow us to display a list of only events, but not articles and photos</p></li>
        <li style='display:none'><h2>Content types and fields</h2>
        <p>In Drupal, content types are made of <em>fields</em> which hold individual pieces of information</p>
        <p>Each field has a type, like text, date, or image.</p>
        <p>Just like with content types, you can define your own fields.</li>
        <li style='display:none'><h2>Content types and fields</h2>
        <p>What if you wanted to display all articles and photos from a single location?</p>
        <p>It's possible because fields can be shared between contnet types, forming relationships between your content.</li>
        <li style='display:none'><h2>Change how your website looks with themes</h2>
        <p><em>Themes</em> change your websites appearance.</p>
        <p>You can download  themes created by the Drupal community, or you can create your own</p></li>
        <li style='display:none'><h2>Drupals functionality is extended with modules</h2>
        <p>Out of the box, Drupal is very limited</p>
        <p>Installing modules adds functionality to your Drupal site.</p>
        <p>The Drupal commnity has made thousands of modules that do practically everything!</p>
        </li>
        <li style='display:none'><h2>Modules</h2>
        <p>How to use a module</p>
        <p>1. Install from Drupal.org</p><p>2. Enable on the modules page</p><p>3. Configure if necessary</p></li>
        <li style='display:none'><h2>Drupal's rich community means lots of modules</h2>
        <p>Drupal websites depend on modules contributed by the community.</p></li>
        <li style='display:none'><img src='http://i29.photobucket.com/albums/c275/electricnomad/Animated%20GIF/RickAstley.gif' /></li>
            </ul>
    </div>";
    drupal_set_message($message,'modal');
    
drupal_add_css(drupal_get_path('module', 'onramp') . '/onramp.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));

drupal_add_js(drupal_get_path('module', 'onramp') . '/swipe.js');

drupal_add_js(drupal_get_path('module', 'onramp') . '/script.js');
}
}


